### ISSUE TITLE
Issue with numpy and lmfit?

### ISSUE THREAD

**Issue by asteppke** [lmfit/lmfit-py#441]
Hello,

In the process of getting to know the lmfit package I started with one of the examples from the documentation ([parameters](https://lmfit.github.io/lmfit-py/parameters.html)) as follows:

```python
from lmfit import minimize, Minimizer, Parameters, Parameter, report_fit
import numpy as np

# create data to be fitted
x = np.linspace(0, 15, 301)
data = (5. * np.sin(2 * x - 0.1) * np.exp(-x*x*0.025) +
        np.random.normal(size=len(x), scale=0.2) )

# define objective function: returns the array to be minimized
def fcn2min(params, x, data):
    """ model decaying sine wave, subtract data"""
    amp = params['amp']
    shift = params['shift']
    omega = params['omega']
    decay = params['decay']
    model = amp * np.sin(x * omega + shift) * np.exp(-x*x*decay)
    return model - data

# create a set of Parameters
params = Parameters()
params.add('amp',   value= 10,  min=0)
params.add('decay', value= 0.1)
params.add('shift', value= 0.0, min=-np.pi/2., max=np.pi/2)
params.add('omega', value= 3.0)


# do fit, here with leastsq model
minner = Minimizer(fcn2min, params, fcn_args=(x, data))
result = minner.minimize()
```

This leads unfortunately to an Attribute Error:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-1-a9bea3fb1219> in <module>()
         27 # do fit, here with leastsq model
         28 minner = Minimizer(fcn2min, params, fcn_args=(x, data))
    ---> 29 result = minner.minimize()
         30 
         31 # calculate final result

    //anaconda/lib/python3.5/site-packages/lmfit/minimizer.py in minimize(self, method, params, **kws)
       1087         elif user_method.startswith('lbfgsb'):
       1088             function = self.lbfgsb
    -> 1089         return function(**kwargs)
       1090 
       1091 

    //anaconda/lib/python3.5/site-packages/lmfit/minimizer.py in leastsq(self, params, **kws)
        929         np.seterr(all='ignore')
        930 
    --> 931         lsout = scipy_leastsq(self.__residual, vars, **lskws)
        932         _best, _cov, infodict, errmsg, ier = lsout
        933         result.aborted = self._abort

    //anaconda/lib/python3.5/site-packages/scipy/optimize/minpack.py in leastsq(func, x0, args, Dfun, full_output, col_deriv, ftol, xtol, gtol, maxfev, epsfcn, factor, diag)
        375     if not isinstance(args, tuple):
        376         args = (args,)
    --> 377     shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
        378     m = shape[0]
        379     if n > m:

    //anaconda/lib/python3.5/site-packages/scipy/optimize/minpack.py in _check_func(checker, argname, thefunc, x0, args, numinputs, output_shape)
         24 def _check_func(checker, argname, thefunc, x0, args, numinputs,
         25                 output_shape=None):
    ---> 26     res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
         27     if (output_shape is not None) and (shape(res) != output_shape):
         28         if (output_shape[0] != 1):

    //anaconda/lib/python3.5/site-packages/lmfit/minimizer.py in __residual(self, fvars)
        288 
        289         params.update_constraints()
    --> 290         out = self.userfcn(params, *self.userargs, **self.userkws)
        291         if callable(self.iter_cb):
        292             abort = self.iter_cb(params, self.result.nfev, out,

    <ipython-input-1-a9bea3fb1219> in fcn2min(params, x, data)
         14     omega = params['omega']
         15     decay = params['decay']
    ---> 16     model = amp * np.sin(x * omega + shift) * np.exp(-x*x*decay)
         17     return model - data
         18 

    AttributeError: 'numpy.float64' object has no attribute 'sin'

So something is going wrong in the interaction between lmfit and numpy. This occurs on Python 3.5.4, numpy 1.13.3 and lmfit 0.9.3.

**Comment by newville** [comment]
@asteppke This works with the latest version (0.9.7) which almost certainly corresponds to the doc you were reading.  

Please use the mailing list for questions and reserve Github Issues for actual Issues.

**Comment by asteppke** [comment]
Thank you for the information. I can confirm that after updating lmfit to 0.9.7 the error does not occur anymore.
